[tool.poetry]
name = "homework31"
version = "0.1.0"
description = ""
authors = ["Andrey Khomutov <homutovan@live.com>"]

[tool.poetry.dependencies]
python = "^3.7"
grab = "^0.6.41"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
